# Write a function nearly_equal to test whether two strings are nearly equal.
# Two strings a and b are nearly equal when a can be generated by a single mutation on b.
def nearly_equal(a, b):
    if a == b:
        return True
    
    if abs(len(a) - len(b)) > 1:
        return False

    i = j = diff = 0

    while i < len(a) and j < len(b):
        if a[i] != b[j]:
            diff += 1
            if diff > 1:
                return False
            if len(a) > len(b):
                i += 1
                continue
            elif len(b) > len(a):
                j += 1
                continue
        i += 1
        j += 1

    return True

print(nearly_equal("book", "books"))   # True
print(nearly_equal("cat", "cut"))      # True
print(nearly_equal("cat", "dog"))      # False
